### ISSUE TITLE
Confusing to use with other 'heavy' (transpiling) loaders

### ISSUE THREAD

**Issue by gregglind** [gowravshekar/bootstrap-webpack#13]
Thanks for trying to tame bootstrap's complexity!

As noted in #3, it is challenging to use this with other loaders including Babel, JSX.  

1.  At the very least some README points about this would help.  
2.  I also don't really understand *why* this is an issue :)  With other loaders, I can add them to the 'loaders' section, and add a test.

**Comment by gowravshekar** [comment]
Updated README.
