### ISSUE TITLE
Incomplete regexp for woff files in example

### ISSUE THREAD

**Issue by phtrivier** [gowravshekar/bootstrap-webpack#15]
Seems like the example line does not work

      { test: /\.woff$/,   loader: "url-loader?limit=10000&mimetype=application/font-woff" },

I stumbled on the same issue as : https://github.com/webpack/less-loader/issues/44

This seems to work (at least it compiles)

     { test: /\.(woff|woff2)$/,   loader: "url-loader?limit=10000&mimetype=application/font-woff" },

**Comment by DannyDelott** [comment]
This helped me! Thanks!

**Comment by gowravshekar** [comment]
Updated README.

**Comment by phtrivier** [comment]
Thanks.
