### ISSUE TITLE
Config not producing correct styles

### ISSUE THREAD

**Issue by tarciosaraiva** [gowravshekar/bootstrap-webpack#18]
Hi there,
I've managed to get plugin working successfully and responding to changes in the config file but the styles are a bit off.

Here are some examples:

<img width="897" alt="screen shot 2016-01-04 at 10 02 42 pm" src="https://cloud.githubusercontent.com/assets/893428/12088403/f5c42c0a-b32e-11e5-9e09-9529995f8475.png">
* note the space between the cells

<img width="477" alt="screen shot 2016-01-04 at 10 02 56 pm" src="https://cloud.githubusercontent.com/assets/893428/12088410/0352fbe4-b32f-11e5-8cee-ff1014a8732c.png">
* note the lack of space between the buttons

**Most of it is fine though. I've compared against Bootstrap itself and the style seems fine, something else is throwing it off. If I just pull in the CSS from a CDN it all looks fine.**

Here's my config:

```
var path    = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

var DIST = path.resolve(__dirname, '../dist');
var APP  = path.resolve(__dirname, '../src/app');
var WEB  = path.resolve(__dirname, '../src/web');

module.exports = {
  entry: [
    'bootstrap-webpack!./config/bootstrap.config.js',
    path.resolve(APP, 'index.js')
  ],
  output: {
    path: DIST,
    filename: 'scripts/bundle.js'
  },
  devServer: {
    historyApiFallback: true,
    contentBase: DIST
  },
  debug: true,
  module: {
    loaders: [
      {
        loader: 'babel-loader',
        test: APP,
        exclude: /node_modules/,
        query: { presets: ['es2015', 'react'] }
      },
      { test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },
      { test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff' },
      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream' },
      { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file' },
      { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml' },
    ]
  },
  plugins: [
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      API_HOST: JSON.stringify((process.env.API_HOST ? process.env.API_HOST : 'http://localhost:8000'))
    }),
    new HtmlWebpackPlugin({
      title: 'Heading',
      hash: true,
      template: path.resolve(WEB, 'index.html'),
      inject: false
    })
  ],
  devtool: 'source-map'
};
```

I'm using `bootstrap@3.3.6`.

Little help?

**Comment by gowravshekar** [comment]
Include only one style in your `bootstrap.config.js`, say buttons. Later you can compare the contents of the generated file with the buttons.less converted to css. This will help to debug the issue easily. You can also create a gist with bare minimums to reproduce the issue.

**Comment by gowravshekar** [comment]
Closed. No further inputs received.

**Comment by sundyxfan** [comment]
How to engage in the production environment ?  @gowravshekar @tarciosaraiva

**Comment by gowravshekar** [comment]
@sundyxfan , Can you please elaborate your question.
