### ISSUE TITLE
I recomed integrating with and syncing bs version to: https://github.com/valor-software/ng2-bootstrap 

### ISSUE THREAD

**Issue by born2net** [gowravshekar/bootstrap-webpack#20]
this is a great project and so I recommend integrating with and syncing bs version to: https://github.com/valor-software/ng2-bootstrap 

Regards,

Sean

Checkout the Ultimate Angular 2 Boorstrap App: @ http://ng2.javascriptninja.io
Source@ https://github.com/born2net/ng2Boilerplate

**Comment by gowravshekar** [comment]
Use a custom configuration with no scripts included and just the styles you needed - https://github.com/gowravshekar/bootstrap-webpack#bootstrapconfigless
