### ISSUE TITLE
Unmet dependencies ..

### ISSUE THREAD

**Issue by durino13** [gowravshekar/bootstrap-webpack#22]
When I have installed bootstrap-webpack, I got following unmet dependencies:

npm WARN less-loader@2.2.2 requires a peer of less@^2.3.1 but none was installed.
npm WARN bootstrap-webpack@0.0.5 requires a peer of url-loader@>=0.5.5 but none was installed.
npm WARN bootstrap-webpack@0.0.5 requires a peer of file-loader@>=0.8.1 but none was installed.
npm WARN bootstrap-webpack@0.0.5 requires a peer of exports-loader@>=0.6.2 but none was installed.
npm WARN bootstrap-webpack@0.0.5 requires a peer of extract-text-webpack-plugin@>=0.3.8 but none was installed.

Any idea, what can I do with this?

Thx.

**Comment by brndusic** [comment]
Same problem, can anyone help?

**Comment by gowravshekar** [comment]
npm is warning about the unmet dependencies. Install the missing dependencies.

`npm install less url-loader file-loader exports-loader extract-text-webpack-plugin `

**Comment by moneer99** [comment]
Same here. Any thoughts?
user:~/home/user/client$ npm install extract-text-webpack-plugin@2.0.0-beta.4 --save
/home/user/client
└── UNMET PEER DEPENDENCY extract-text-webpack-plugin@2.0.0-beta.4

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN bootstrap-webpack@0.0.5 requires a peer of extract-text-webpack-plugin@>=0.3.8 but none was installed.
npm WARN client No repository field.
npm WARN client No license field.
npm ERR! code 1
