### ISSUE TITLE
bootstrap.config.js doesn't work (in my config)

### ISSUE THREAD

**Issue by bahlo** [gowravshekar/bootstrap-webpack#27]
Hello,

first: Thanks for creating this library, it works like a charm.

I created a `bootstrap.config.js` in `__dir/src/bootstrap/bootstrap.config.js` with the [example contents](https://github.com/gowravshekar/bootstrap-webpack#bootstrapconfigjs) and updated my `webpack.base.conf.js` to the following:

```javascript
module.exports = {
  entry: {
    app: [
      'bootstrap-webpack!./src/bootstrap/bootstrap.config.js',
      './src/main.js'
    ]
  },
  // ...
  module: {
    preLoaders: [
      {
        test: /\.vue$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'eslint',
        include: projectRoot,
        exclude: /node_modules/
      }
    ]
  }
}
```

When I build the app, I get the following error:
```
ERROR in ./~/bootstrap-webpack/bootstrap-scripts.loader.js!./src/bootstrap/bootstrap.config.js
Module build failed: Error: Cannot find module '/Users/arne/Developer/group/app/node_modules/eslint-loader/index.js!/Users/arne/Developer/group/app/src/bootstrap/bootstrap.config.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.pitch (/Users/arne/Developer/group/app/node_modules/bootstrap-webpack/bootstrap-scripts.loader.js:20:16)
 @ ./~/bootstrap-webpack/index.loader.js!./src/bootstrap/bootstrap.config.js 2:0-225
```

So it seems he can't find `eslint-loader` or the `bootstrap.config.js`, but both files exist.
Plus when I get syntax errors on the file (when I remove the `=`, i get `Unexpected token {`).

I also tried prepending `!`, `!!` and `-!` but with not effects.

Any idea how to handle this? Thanks in advance! :+1:

**Comment by gowravshekar** [comment]
Exclude bootstrap folder from `test: /\.js$/`

```javascript```
{
    test: /\.js$/,
    loader: 'eslint',
    include: projectRoot,
    exclude: [
        /node_modules/,
        --path-to-bootstrap-folder--
    ]
}
```

**Comment by bahlo** [comment]
Thank you, Gowrav, I'll try that tomorrow - feel free to close this for now. 👍

**Comment by bahlo** [comment]
It works, thank you - I'm still getting started with WebPack 👌🙈
