### ISSUE TITLE
Advice on peerDependencies vs dependencies

### ISSUE THREAD

**Issue by justin808** [gowravshekar/bootstrap-webpack#4]
I'm maintaining similar project: https://github.com/justin808/bootstrap-sass-loader

Wondering if other loaders should be peerDependencies or dependencies in package.json:

https://github.com/gowravshekar/bootstrap-webpack/blob/master/package.json#L18

```
  "dependencies": {
    "css-loader": "~0.6.3",
    "less-loader": "~0.6.2",
    "style-loader": "~0.6.0"
  },
  "peerDependencies": {
    "bootstrap": ">=3.0.2"
  }
```

**Comment by bebraw** [comment]
I think peer dependencies are the way to go. I've used that for React components. The problem with direct dependencies is that you can easily end up with multiple different versions of the same dependency in your bundle. Peer dependencies avoid that and it's up to user to pick the right version to use. It's a good idea to keep peer dependencies pretty loose (up to next major version or something).

**Comment by gowravshekar** [comment]
Added loaders in peerDependencies.
