### ISSUE TITLE
Handle Bootstrap's jQuery dependency

### ISSUE THREAD

**Issue by wosc** [gowravshekar/bootstrap-webpack#7]
Straight up with a `require("bootstrap-webpack");` my browser says "ReferenceError: jQuery is not defined" with most of Bootstrap's script modules.

I've added `jquery` as a dependency in package.json and this in webpack.config.js to fix it:

```javascript
module: {
    loaders: [
        {
            test: /\/bootstrap\/js\//,
            loader: "imports?jQuery=jquery"
        },
}
```

**Comment by gowravshekar** [comment]
You need to expose the (jquery, $) variables for other third party libraries to use.
Use this in your entry script

```js
require('expose?$!expose?jQuery!jquery');
```

Also webpack as an argument called ```--display-error-details``` that will help you debug stuff like this.
